---
title: "Probability and Statistics Fundamentals (Session 2)"
output:
  html_document:
    toc: true
    toc_float: false
    number_sections: true
---

# Hello
Blabla this section introduces you to bla

# Random Variables
Random variables are variables that take on numerical values and are determined by experiments. Mathematically speaking, probability experiments (or trials) are procedures which can be infinitely repeated and which have a well-defined set of possible outcomes. These outcomes are affected by chance. This shall be explained by an example. The simplest probability experiment is certainly the coin toss. In theory, it can be infinitely repeated and it also has a well-defined set of outcomes, namely heads or tails. Now lets assign the value $1$ to heads and $0$ to tails. So our variable, let's call it $X$ can take on either $1$ or $0$ but unless we perform an experiment (a coin toss!), the value it takes on remains essentially *random*, i.e. it is determined by chance.

## A few notational remarks
We normally denote a random variable by a capital letter such as $X$ or $Y$. We use small letters $x$ or $y$ when we talk about realisations of $X$ or $Y$, i.e. observations that we have made by performing an experiment. For example, when $X$ is our variable for the possible outcomes of a coin toss, and we perform a coin toss, $x$ denotes a particular outcome of $X$, for example, $1$, or heads, respectively.
Looking at different experiments of the same kind


 - Notational Remarks ($X$ or $x_i$, and what about $Y$?)
    - $X$ is a random variable, $x$ is a particular outcome.

## Discrete random variables
Discrete random variables are variables which can only take a countable number of values. For example, throwing a  die represents a random variable. For this example, let $D$ be a random variable with outcomes $j = 1, 2, 3, 4, 5, 6$, then:  
$$p_j = P(D = d_j), j = 1, 2, 3, 4, 5, 6$$  
with $p_1 + p_2 + ... + p_6 = 1$.  
This reads "The Probability of $D$ to take $d_j$ is $p_j$". Each $p_j$ is between $0$ and $1$ and all of them add up to $1$. Why? Because there is a certain probability for every side of a die that it will be thrown, and if you add those probabilities together, they have to add up to 100%! Obviously, the probability of throwing a 7 with a common 6-side die is 0%. If the die is fair, each $p_j$ is $\frac{1}{6}$

# Probability Density Functions and Cumulative Density Functions

